apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: %%%PODNAME%%%
  namespace: %%%NAMESPACE%%%
  labels:
    app: gpfs-cli%%%NUMBER%%%
    role: gpfs-cli
spec:
  selector:
    matchLabels:
      app: gpfs-cli%%%NUMBER%%%
      role: gpfs-cli
  serviceName: &name gpfs-cli%%%NUMBER%%%
  replicas: 1
  template:
    metadata:
      name: &name gpfs-cli%%%NUMBER%%%
      labels:
        app: *name
        role: gpfs-cli
      annotations:
        "cni.projectcalico.org/ipAddrs": "[\"%%%POD_IP%%%\"]"
    spec:
      hostNetwork: false
      nodeName: %%%NODENAME%%%
      containers:
      - name: %%%PODNAME%%%
        image: %%%IMAGE_REPO%%%:%%%IMAGE_TAG%%%
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "./scripts/init-container.sh" ]
        env:        
        - name: FS_NAME
          value: %%%FS_NAME%%%
        securityContext:
          privileged: true
        readinessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
          - name: init-container
            mountPath: /scripts/init-container.sh
            subPath: init-container.sh
          - name: installdir
            mountPath: /usr/lpp
          - name: hostsfile
            mountPath: /etc/hosts
          - name: gendir
            mountPath: /var/mmfs
          - name: etcsshdir
            mountPath: /root/ssh
          - name: rootsshdir
            mountPath: /root/.ssh
      volumes:
      - name: init-container
        configMap:
          name: init-container
          defaultMode: 0755
      - name: installdir
        hostPath:
          path: /usr/lpp
          type: Directory
      - name: hostsfile
        hostPath:
          path: /root/cli%%%NUMBER%%%/hosts
          type: File
      - name: gendir
        hostPath:
          path: /root/cli%%%NUMBER%%%/var_mmfs
          type: Directory
      - name: etcsshdir
        hostPath:
          path: /root/cli%%%NUMBER%%%/etc_ssh
          type: Directory
      - name: rootsshdir
        hostPath:
          path: /root/cli%%%NUMBER%%%/root_ssh
          type: Directory
