apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-server-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 10Gi
