{
 "title": "GPFS Performance",
 "description": "GPFS dashboard for Prometheus GPFS exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "topk", "label": "Top Clients", "query": "5,10,15,20" },
   { "name": "fs", "query": "ess,project,scratch" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(gpfs_perf_read_bytes_total{fs=~\"$fs\",role=\"compute\"}, cluster)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(gpfs_perf_read_bytes_total{fs=~\"$fs\",cluster=\"$cluster\",role=\"compute\"}, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Filesystem Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1.0 - (sum(gpfs_fs_free_bytes{fs=~\"$fs\"}) / sum(gpfs_fs_size_bytes{fs=~\"$fs\"}))"
    }
   ]
  },
  {
   "title": "Inodes Used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gpfs_fs_used_inodes{fs=~\"$fs\"}) / sum(gpfs_fs_inodes{fs=~\"$fs\"})"
    }
   ]
  },
  {
   "title": "Inodes Allocated",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gpfs_fs_allocated_inodes{fs=~\"$fs\"}) / sum(gpfs_fs_inodes{fs=~\"$fs\"})"
    }
   ]
  },
  {
   "title": "Metadata Used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1.0 - (sum(gpfs_fs_metadata_free_bytes{fs=~\"$fs\"}) / sum(gpfs_fs_metadata_size_bytes{fs=~\"$fs\"}))"
    }
   ]
  },
  { "title": "GPFS IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "GPFS Read IO",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gpfs_perf_read_bytes_total{fs=~\"$fs\",cluster=~\"$cluster\",host=~\"$host\"}[15m])) by (fs)",
     "legendFormat": "{{fs}}"
    }
   ]
  },
  {
   "title": "GPFS Write IO",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gpfs_perf_write_bytes_total{fs=~\"$fs\",cluster=~\"$cluster\",host=~\"$host\"}[15m])) by (fs)",
     "legendFormat": "{{fs}}"
    }
   ]
  },
  {
   "title": "GPFS Read IO - Top Clients",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk($topk, irate(gpfs_perf_read_bytes_total{fs=~\"$fs\",cluster=~\"$cluster\"}[15m]))",
     "legendFormat": "{{host}} - {{fs}}"
    }
   ]
  },
  {
   "title": "GPFS Write IO - Top Clients",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk($topk, irate(gpfs_perf_write_bytes_total{fs=~\"$fs\",cluster=~\"$cluster\"}[15m]))",
     "legendFormat": "{{host}} - {{fs}}"
    }
   ]
  },
  { "title": "GPFS Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "GPFS Read Operations",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gpfs_perf_operations_total{fs=~\"$fs\",cluster=~\"$cluster\",host=~\"$host\",operation=\"reads\"}[15m])) by (fs)",
     "legendFormat": "{{fs}}"
    }
   ]
  },
  {
   "title": "GPFS Write Operations",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gpfs_perf_operations_total{fs=~\"$fs\",cluster=~\"$cluster\",host=~\"$host\",operation=\"writes\"}[15m])) by (fs)",
     "legendFormat": "{{fs}}"
    }
   ]
  },
  {
   "title": "GPFS Read Operations - Top Clients",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk($topk, irate(gpfs_perf_operations_total{fs=~\"$fs\",cluster=~\"$cluster\",operation=\"reads\"}[15m]))",
     "legendFormat": "{{host}} - {{fs}}"
    }
   ]
  },
  {
   "title": "GPFS Write Operations - Top Clients",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk($topk, irate(gpfs_perf_operations_total{fs=~\"$fs\",cluster=~\"$cluster\",operation=\"writes\"}[15m]))",
     "legendFormat": "{{host}} - {{fs}}"
    }
   ]
  },
  {
   "title": "GPFS Metadata Operations",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gpfs_perf_operations_total{fs=~\"$fs\",cluster=~\"$cluster\",host=~\"$host\",operation=~\"(closes|inode_updates|opens|read_dir)\"}[15m])) by (fs)",
     "legendFormat": "{{fs}}"
    }
   ]
  },
  {
   "title": "GPFS Metadata Operations - Top Clients",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk($topk, sum(irate(gpfs_perf_operations_total{fs=~\"$fs\",cluster=~\"$cluster\",operation=~\"(closes|inode_updates|opens|read_dir)\"}[15m])) by (host,fs))",
     "legendFormat": "{{host}} - {{fs}}"
    }
   ]
  }
 ]
}