---
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-indigo-%%%CLUSTER_NAME%%%
  namespace: %%%NAMESPACE%%%
data:
  application-indigo.yml: |
    spring:
      security:
        oauth2:
          client:
            provider:
              iam-indigo:
                issuer-uri: https://%%%OIDC_PROVIDER%%%/
            registration:
              iam-indigo:
                provider: iam-indigo
                authorization-grant-type: authorization_code
                client-name: INDIGO IAM
                client-id: %%%OIDC_CLIENT_ID%%%
                client-secret: %%%OIDC_CLIENT_SECRET%%%
                scope:
                  - openid
                  - profile
    oauth:
      enable-oidc: true
      issuers:
        - name: iam-indigo
          issuer: https://%%%OIDC_PROVIDER%%%/

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-area-%%%CLUSTER_NAME%%%
  namespace: %%%NAMESPACE%%%
data:
  sa.properties: |
    # Name of the storage area
    name=indigo-dc
    # Root path for the storage area. Files will be served from this path, which must exist and
    # must be accessible from the user that runs the storm webdav service
    rootPath=/ibm/%%%FS_NAME%%%
    # Comma separated list of storage area access points. 
    accessPoints=/indigo-dc
    # Comma-separated list of OAuth/OpenID Connect token issuers trusted in this storage area
    orgs=https://%%%OIDC_PROVIDER%%%/
    # Enables write access to storage area files to users authenticated using OAuth/OIDC. Defaults to false.
    orgsGrantWritePermission=true
